name: m2sbench
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pyyaml
  - matplotlib
  - scikit-learn
  - scipy
  - pyarrow
  - pytest
  - pip
  - pip:
      - xgboost
      - hmmlearn
      - POT
      - statsmodels
      - openai
